//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NetflixUI.NetflixWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NetflixWSSoap", Namespace="http://tempuri.org/")]
    public partial class NetflixWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PayOperationCompleted;
        
        private System.Threading.SendOrPostCallback CanPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserLatesPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsPaidOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NetflixWS() {
            this.Url = global::NetflixUI.Properties.Settings.Default.NetflixUI_localhost_NetflixWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PayCompletedEventHandler PayCompleted;
        
        /// <remarks/>
        public event CanPayCompletedEventHandler CanPayCompleted;
        
        /// <remarks/>
        public event IncomeCompletedEventHandler IncomeCompleted;
        
        /// <remarks/>
        public event UserLatesPayCompletedEventHandler UserLatesPayCompleted;
        
        /// <remarks/>
        public event UserPaymentCompletedEventHandler UserPaymentCompleted;
        
        /// <remarks/>
        public event IsPaidCompletedEventHandler IsPaidCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Pay(Card c, Transaction t) {
            object[] results = this.Invoke("Pay", new object[] {
                        c,
                        t});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PayAsync(Card c, Transaction t) {
            this.PayAsync(c, t, null);
        }
        
        /// <remarks/>
        public void PayAsync(Card c, Transaction t, object userState) {
            if ((this.PayOperationCompleted == null)) {
                this.PayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPayOperationCompleted);
            }
            this.InvokeAsync("Pay", new object[] {
                        c,
                        t}, this.PayOperationCompleted, userState);
        }
        
        private void OnPayOperationCompleted(object arg) {
            if ((this.PayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PayCompleted(this, new PayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CanPay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CanPay(Card c, Transaction t) {
            object[] results = this.Invoke("CanPay", new object[] {
                        c,
                        t});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CanPayAsync(Card c, Transaction t) {
            this.CanPayAsync(c, t, null);
        }
        
        /// <remarks/>
        public void CanPayAsync(Card c, Transaction t, object userState) {
            if ((this.CanPayOperationCompleted == null)) {
                this.CanPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCanPayOperationCompleted);
            }
            this.InvokeAsync("CanPay", new object[] {
                        c,
                        t}, this.CanPayOperationCompleted, userState);
        }
        
        private void OnCanPayOperationCompleted(object arg) {
            if ((this.CanPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CanPayCompleted(this, new CanPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Income", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transaction[] Income(string payee) {
            object[] results = this.Invoke("Income", new object[] {
                        payee});
            return ((Transaction[])(results[0]));
        }
        
        /// <remarks/>
        public void IncomeAsync(string payee) {
            this.IncomeAsync(payee, null);
        }
        
        /// <remarks/>
        public void IncomeAsync(string payee, object userState) {
            if ((this.IncomeOperationCompleted == null)) {
                this.IncomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncomeOperationCompleted);
            }
            this.InvokeAsync("Income", new object[] {
                        payee}, this.IncomeOperationCompleted, userState);
        }
        
        private void OnIncomeOperationCompleted(object arg) {
            if ((this.IncomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncomeCompleted(this, new IncomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserLatesPay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transaction UserLatesPay(string payee, string card) {
            object[] results = this.Invoke("UserLatesPay", new object[] {
                        payee,
                        card});
            return ((Transaction)(results[0]));
        }
        
        /// <remarks/>
        public void UserLatesPayAsync(string payee, string card) {
            this.UserLatesPayAsync(payee, card, null);
        }
        
        /// <remarks/>
        public void UserLatesPayAsync(string payee, string card, object userState) {
            if ((this.UserLatesPayOperationCompleted == null)) {
                this.UserLatesPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserLatesPayOperationCompleted);
            }
            this.InvokeAsync("UserLatesPay", new object[] {
                        payee,
                        card}, this.UserLatesPayOperationCompleted, userState);
        }
        
        private void OnUserLatesPayOperationCompleted(object arg) {
            if ((this.UserLatesPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserLatesPayCompleted(this, new UserLatesPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Card UserPayment(string card) {
            object[] results = this.Invoke("UserPayment", new object[] {
                        card});
            return ((Card)(results[0]));
        }
        
        /// <remarks/>
        public void UserPaymentAsync(string card) {
            this.UserPaymentAsync(card, null);
        }
        
        /// <remarks/>
        public void UserPaymentAsync(string card, object userState) {
            if ((this.UserPaymentOperationCompleted == null)) {
                this.UserPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserPaymentOperationCompleted);
            }
            this.InvokeAsync("UserPayment", new object[] {
                        card}, this.UserPaymentOperationCompleted, userState);
        }
        
        private void OnUserPaymentOperationCompleted(object arg) {
            if ((this.UserPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserPaymentCompleted(this, new UserPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsPaid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsPaid(string payee, string card) {
            object[] results = this.Invoke("IsPaid", new object[] {
                        payee,
                        card});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsPaidAsync(string payee, string card) {
            this.IsPaidAsync(payee, card, null);
        }
        
        /// <remarks/>
        public void IsPaidAsync(string payee, string card, object userState) {
            if ((this.IsPaidOperationCompleted == null)) {
                this.IsPaidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsPaidOperationCompleted);
            }
            this.InvokeAsync("IsPaid", new object[] {
                        payee,
                        card}, this.IsPaidOperationCompleted, userState);
        }
        
        private void OnIsPaidOperationCompleted(object arg) {
            if ((this.IsPaidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsPaidCompleted(this, new IsPaidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Card {
        
        private string cardNumberField;
        
        private int ownerField;
        
        private int cVVField;
        
        private int expMonthField;
        
        private int expYearField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private int balanceField;
        
        /// <remarks/>
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public int Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        public int CVV {
            get {
                return this.cVVField;
            }
            set {
                this.cVVField = value;
            }
        }
        
        /// <remarks/>
        public int ExpMonth {
            get {
                return this.expMonthField;
            }
            set {
                this.expMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ExpYear {
            get {
                return this.expYearField;
            }
            set {
                this.expYearField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public int Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Transaction {
        
        private int idField;
        
        private string cardNumberField;
        
        private int amountField;
        
        private string payeeField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string Payee {
            get {
                return this.payeeField;
            }
            set {
                this.payeeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PayCompletedEventHandler(object sender, PayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CanPayCompletedEventHandler(object sender, CanPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CanPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CanPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void IncomeCompletedEventHandler(object sender, IncomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transaction[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transaction[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UserLatesPayCompletedEventHandler(object sender, UserLatesPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserLatesPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserLatesPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transaction Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transaction)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UserPaymentCompletedEventHandler(object sender, UserPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Card Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Card)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void IsPaidCompletedEventHandler(object sender, IsPaidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsPaidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsPaidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591